name: nc-digits
channels:
  - defaults
  - nvidia
  - pytorch
  - conda-forge
dependencies:
  - python==3.11
  - scipy>=1.14.1
  - matplotlib>=3.9.2
  - scikit-learn>=1.5.2
  - pandas[computation,performance]>=2.2.3
  - ipywidgets>=8.1.5
  - pytorch-cuda=12.4
  - pytorch>=2.4.0
  - torchvision>=0.20.1
  - brian2>=1.4.4
  - snntorch>=0.9.1
  - jupyter>=1.1.1
  - jupyterlab>=4.2.0
  - notebook>=7.2.2
  - ffmpeg>=1.4
  - tonic>=1.5.0
  - tqdm>=4.67.1
  - opencv>=4.10.0
  - torchmetrics>=1.6.1
  - pip
  - pip:
    - brian2genn>=1.7.0
    - dv-processing>=1.7.9
    - -e .[dev]
